# -*- coding: utf-8 -*-
"""Movie DB API.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1g4fMztgt2MqRS_kvBkl9sjZqVB1zv1kW
"""

!pip install pandas
!pip install requests
import pandas as pd
import requests

#Extract top rated movies from themoviedv. Link below is where we extract this from
#https://www.themoviedb.org/movie/top-rated
response = requests.get('https://api.themoviedb.org/3/movie/top_rated?api_key=e8f47b23e6250bc0d8cb662b80682a91&language=en-US&page=1').json()

#This is the format of 'json' data. How we will pull
print(response)

#Extracting results subsection
print(response['results'])

#Take all data from 'results' subcategory. Place into pandas dataframe
data = pd.DataFrame(response['results'])

#Print the dataset
display(data)

#Subset dataset. Select desired columns from above using pandas
target_pd = data[['original_title', 'popularity', 'overview']]

#Extracting specific fields from API json data.
title = []
popularity = []
overview = []

for item in response['results']:
  title.append(item['original_title'])
  popularity.append(item['popularity'])
  overview.append(item['overview'])

target_api = pd.DataFrame({
    'title': title,
    'popularity': popularity,
    'overview': overview
})

#Display datasets
display(target_pd)

display(target_api)

#Go to following page and extract that information. Append to dataset.
response = requests.get('https://api.themoviedb.org/3/movie/top_rated?api_key=e8f47b23e6250bc0d8cb662b80682a91&language=en-US&page=2').json()
data = pd.DataFrame(response['results'])
display(data)

#Loop to go through multiple pages
#Go through 3 pages. 20 results per page.
page = 1
URL = 'https://api.themoviedb.org/3/movie/top_rated?api_key=e8f47b23e6250bc0d8cb662b80682a91&language=en-US&page='
#Create empty dataframe
title = []
popularity = []
overview = []

while page < 4:
  web_url = URL + str(page)
  response = requests.get(web_url).json()
  #Increment page
  page = page + 1
  for item in response['results']:
    title.append(item['original_title'])
    popularity.append(item['popularity'])
    overview.append(item['overview'])

target_api = pd.DataFrame({
    'title': title,
    'popularity': popularity,
    'overview': overview
})

display(target_api)

#Sources
#https://www.enjoyalgorithms.com/blog/api-introduction-for-data-science-and-ml
#https://www.themoviedb.org/movie/top-rated